# Generated by Django 3.0.7 on 2020-09-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='thread',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
